# Generated by Django 5.0.2 on 2024-07-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
