# Generated by Django 5.0.2 on 2024-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/Researcher'), ('user', 'Regular User')], default='user', max_length=10),
        ),
    ]
